- name: Create tomcat group
  group:
    state: present
    name: tomcat

- name: Create directory for tomcat
  file:
    path: /opt/tomcat
    state: directory

- name: install tomcat
  yum:
    name: "{{ item }}"
    state: present
    dest: /opt/tomcat
  with_items:
    - tomcat8

- name: change tomcat directory permissions
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Create directory for java
  file:
  path: /opt/java
  state: directory

- name: Copy java package
  copy:
  src: /Users/sanjanakadam/Downloads/jre-9.0.4_linux-x64_bin.rpm
  dest: /opt/java

- name: install java 9.0.4
  become: yes
  become_user: root
  command: yum -y localinstall arg jre-9.0.4_linux-x64_bin.rpm
  args:
    chdir: /opt/java/